Collections:
- Name: RDN
  Paper:
    Title: Residual Dense Network for Image Super-Resolution
    URL: https://arxiv.org/abs/1802.08797
  README: configs/rdn/README.md
  Task:
  - image super-resolution
  Year: 2018
Models:
- Config: configs/rdn/rdn_x4c64b16_1xb16-1000k_div2k.py
  In Collection: RDN
  Name: rdn_x4c64b16_1xb16-1000k_div2k
  Results:
  - Dataset: Set5
    Metrics:
      PSNR: 30.4922
      SSIM: 0.8548
    Task: Image Super-Resolution
  - Dataset: Set14
    Metrics:
      PSNR: 26.957
      SSIM: 0.7423
    Task: Image Super-Resolution
  - Dataset: DIV2K
    Metrics:
      PSNR: 29.1925
      SSIM: 0.8233
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/rdn/rdn_x4c64b16_g1_1000k_div2k_20210419-3577d44f.pth
- Config: configs/rdn/rdn_x3c64b16_1xb16-1000k_div2k.py
  In Collection: RDN
  Name: rdn_x3c64b16_1xb16-1000k_div2k
  Results:
  - Dataset: Set5
    Metrics:
      PSNR: 32.6051
      SSIM: 0.8943
    Task: Image Super-Resolution
  - Dataset: Set14
    Metrics:
      PSNR: 28.6338
      SSIM: 0.8077
    Task: Image Super-Resolution
  - Dataset: DIV2K
    Metrics:
      PSNR: 31.2153
      SSIM: 0.8763
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/rdn/rdn_x3c64b16_g1_1000k_div2k_20210419-b93cb6aa.pth
- Config: configs/rdn/rdn_x2c64b16_1xb16-1000k_div2k.py
  In Collection: RDN
  Name: rdn_x2c64b16_1xb16-1000k_div2k
  Results:
  - Dataset: Set5
    Metrics:
      PSNR: 35.9883
      SSIM: 0.9385
    Task: Image Super-Resolution
  - Dataset: Set14
    Metrics:
      PSNR: 31.8366
      SSIM: 0.892
    Task: Image Super-Resolution
  - Dataset: DIV2K
    Metrics:
      PSNR: 34.9392
      SSIM: 0.938
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/rdn/rdn_x2c64b16_g1_1000k_div2k_20210419-dc146009.pth
