Collections:
- Name: RealBasicVSR
  Paper:
    Title: 'RealBasicVSR: Investigating Tradeoffs in Real-World Video Super-Resolution'
    URL: https://arxiv.org/abs/2111.12704
  README: configs/real_basicvsr/README.md
  Task:
  - video super-resolution
  Year: 2022
Models:
- Config: configs/real_basicvsr/realbasicvsr_c64b20-1x30x8_8xb1-lr5e-5-150k_reds.py
  In Collection: RealBasicVSR
  Name: realbasicvsr_c64b20-1x30x8_8xb1-lr5e-5-150k_reds
  Results:
  - Dataset: REDS
    Metrics:
      BRISQUE (Y): 29.03
      NIQE (Y): 3.7662
      NRQM (Y): 6.0477
      PI (Y): 3.8593
    Task: Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/real_basicvsr/realbasicvsr_c64b20_1x30x8_lr5e-5_150k_reds_20211104-52f77c2c.pth
- Config: configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py
  In Collection: RealBasicVSR
  Name: realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds
  Results:
  - Dataset: REDS
    Metrics: {}
    Task: Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds_20211027-0e2ff207.pth
