Collections:
- Name: EDVR
  Paper:
    Title: 'EDVR: Video Restoration with Enhanced Deformable Convolutional Networks'
    URL: https://arxiv.org/abs/1905.02716?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%253A+arxiv%252FQSXk+%2528ExcitingAds%2521+cs+updates+on+arXiv.org%2529
  README: configs/edvr/README.md
  Task:
  - video super-resolution
  Year: 2019
Models:
- Config: configs/edvr/edvrm_wotsa_8xb4-600k_reds.py
  In Collection: EDVR
  Name: edvrm_wotsa_8xb4-600k_reds
  Results:
  - Dataset: REDS
    Metrics:
      PSNR: 30.343
      SSIM: 0.8664
    Task: Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/edvr/edvrm_wotsa_x4_8x4_600k_reds_20200522-0570e567.pth
- Config: configs/edvr/edvrm_8xb4-600k_reds.py
  In Collection: EDVR
  Name: edvrm_8xb4-600k_reds
  Results:
  - Dataset: REDS
    Metrics:
      PSNR: 30.4194
      SSIM: 0.8684
    Task: Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/edvr/edvrm_x4_8x4_600k_reds_20210625-e29b71b5.pth
- Config: configs/edvr/edvrl_wotsa-c128b40_8xb8-lr2e-4-600k_reds4.py
  In Collection: EDVR
  Name: edvrl_wotsa-c128b40_8xb8-lr2e-4-600k_reds4
  Results:
  - Dataset: REDS
    Metrics:
      PSNR: 31.001
      SSIM: 0.8784
    Task: Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/edvr/edvrl_wotsa_c128b40_8x8_lr2e-4_600k_reds4_20211228-d895a769.pth
- Config: configs/edvr/edvrl_c128b40_8xb8-lr2e-4-600k_reds4.py
  In Collection: EDVR
  Name: edvrl_c128b40_8xb8-lr2e-4-600k_reds4
  Results:
  - Dataset: REDS
    Metrics:
      PSNR: 31.0467
      SSIM: 0.8793
    Task: Video Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/edvr/edvrl_c128b40_8x8_lr2e-4_600k_reds4_20220104-4509865f.pth
