Collections:
- Name: SNGAN
  Paper:
    Title: Spectral Normalization for Generative Adversarial Networks
    URL: https://openreview.net/forum?id=B1QRgziT-
  README: configs/sngan_proj/README.md
  Task:
  - conditional gans
  Year: 2018
Models:
- Config: configs/sngan_proj/sngan-proj_woReLUinplace_lr2e-4-ndisc5-1xb64_cifar10-32x32.py
  In Collection: SNGAN
  Name: sngan-proj_woReLUinplace_lr2e-4-ndisc5-1xb64_cifar10-32x32
  Results:
  - Dataset: CIFAR10
    Metrics:
      FID: 9.8203
      IS: 9.6919
      Iter: 400000.0
      Total Iters\*: 500000.0
      disc_step: 5.0
    Task: Conditional GANs
  - Dataset: CIFAR10
    Metrics:
      FID: 8.1158
      IS: 9.5659
      Iter: 490000.0
      Total Iters\*: 500000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sngan_proj/sngan_proj_cifar10_32_lr-2e-4_b64x1_woReLUinplace_fid-iter490000_20210709_163329-ba0862a0.pth
- Config: configs/sngan_proj/sngan-proj_wReLUinplace_lr2e-4-ndisc5-1xb64_cifar10-32x32.py
  In Collection: SNGAN
  Name: sngan-proj_wReLUinplace_lr2e-4-ndisc5-1xb64_cifar10-32x32
  Results:
  - Dataset: CIFAR10
    Metrics:
      FID: 8.3462
      IS: 9.5564
      Iter: 490000.0
      Total Iters\*: 500000.0
      disc_step: 5.0
    Task: Conditional GANs
  - Dataset: CIFAR10
    Metrics:
      FID: 8.3462
      IS: 9.5564
      Iter: 490000.0
      Total Iters\*: 500000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sngan_proj/sngan_proj_cifar10_32_lr-2e-4-b64x1_wReLUinplace_fid-iter490000_20210709_203038-191b2648.pth
- Config: configs/sngan_proj/sngan-proj_woReLUinplace_Glr2e-4_Dlr5e-5_ndisc5-2xb128_imagenet1k-128x128.py
  In Collection: SNGAN
  Name: sngan-proj_woReLUinplace_Glr2e-4_Dlr5e-5_ndisc5-2xb128_imagenet1k-128x128
  Results:
  - Dataset: ImageNet
    Metrics:
      FID: 33.4682
      IS: 30.0651
      Iter: 952000.0
      Total Iters\*: 1000000.0
      disc_step: 5.0
    Task: Conditional GANs
  - Dataset: ImageNet
    Metrics:
      FID: 32.6193
      IS: 29.5779
      Iter: 989000.0
      Total Iters\*: 1000000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sngan_proj/sngan_proj_imagenet1k_128_Glr2e-4_Dlr5e-5_ndisc5_b128x2_woReLUinplace_fid-iter988000_20210730_131424-061bf803.pth
- Config: configs/sngan_proj/sngan-proj_wReLUinplace_Glr2e-4_Dlr5e-5_ndisc5-2xb128_imagenet1k-128x128.py
  In Collection: SNGAN
  Name: sngan-proj_wReLUinplace_Glr2e-4_Dlr5e-5_ndisc5-2xb128_imagenet1k-128x128
  Results:
  - Dataset: ImageNet
    Metrics:
      FID: 34.3383
      IS: 28.1799
      Iter: 944000.0
      Total Iters\*: 1000000.0
      disc_step: 5.0
    Task: Conditional GANs
  - Dataset: ImageNet
    Metrics:
      FID: 33.4821
      IS: 27.7948
      Iter: 988000.0
      Total Iters\*: 1000000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sngan_proj/sngan_proj_imagenet1k_128_Glr2e-4_Dlr5e-5_ndisc5_b128x2_wReLUinplace_fid-iter988000_20210730_132401-9a682411.pth
- Config: configs/sngan_proj/sngan-proj-cvt-studioGAN_cifar10-32x32.py
  In Collection: SNGAN
  Name: sngan-proj-cvt-studioGAN_cifar10-32x32
  Results:
  - Dataset: CIFAR10
    Metrics:
      FID (Our Pipeline): 10.2011
      FID (StudioGAN): 13.248
      IS (Our Pipeline): 9.372
      IS (StudioGAN): 8.677
      Total Iters: 100000.0
      disc_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sngan_proj/sngan_cifar10_convert-studio-rgb_20210709_111346-2979202d.pth
- Config: configs/sngan_proj/sngan-proj-cvt-studioGAN_imagenet1k-128x128.py
  In Collection: SNGAN
  Name: sngan-proj-cvt-studioGAN_imagenet1k-128x128
  Results:
  - Dataset: ImageNet
    Metrics:
      FID (Our Pipeline): 29.8199
      FID (StudioGAN): 26.792
      IS (Our Pipeline): 30.218
      IS (StudioGAN): 32.247
      Total Iters: 1000000.0
      disc_step: 2.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sngan_proj/sngan_imagenet1k_convert-studio-rgb_20210709_111406-877b1130.pth
