name: "🐞 Bug report"
description: "Create a report to help us reproduce and fix the bug"
labels: bug 
title: "[Bug] "

body:
  - type: markdown
    attributes:
      value: |
        If you have already identified the reason, we strongly appreciate you creating a new PR to fix it [here](https://github.com/open-mmlab/mmediting/pulls)!
        If this issue is about installing MMCV, please file an issue at [MMCV](https://github.com/open-mmlab/mmcv/issues/new/choose).
        If you need our help, please fill in as much of the following form as you're able.
        
        **The less clear the description, the longer it will take to solve it.**

  - type: checkboxes
    attributes:
      label: Prerequisite
      description: Please check the following items before creating a new issue.
      options:
      - label: I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
        required: true
      - label: I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
        required: true
      - label: The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmediting).
        required: true

  - type: textarea
    attributes:
      label: 🐞 Describe the bug
      description: |
        Please provide a clear and concise description (e.g., a minimal code snippet) that we can reproduce the error.
        Did you make any modifications on the code or config? Are you clear about what you have modified?
      placeholder: |
        A clear and concise description of what the bug is.
        ```python
        # Sample code to reproduce the problem
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction
      description: |
        What command or script did you run?
      placeholder: |
        ```shell
        The command or script you run.
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error message
      description: |
        Please provide the error message or logs you got, with the full traceback.
      placeholder: |
        ```
        The error message or logs you got, with the full traceback.
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Please run `python mmedit/utils/collect_env.py` to collect necessary environment information and paste it here.
        You may add additional information that may be helpful for locating the problem, such as
          - How you installed PyTorch \[e.g., pip, conda, source\]
          - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
      placeholder: |
        1. What dataset did you use?
        2. What do you think might be the reason?
