Collections:
- Name: AOT-GAN
  Paper:
    Title: 'AOT-GAN: Aggregated Contextual Transformations for High-Resolution Image
      Inpainting'
    URL: https://arxiv.org/abs/2104.01431.pdf
  README: configs/aot_gan/README.md
  Task:
  - inpainting
  Year: 2021
Models:
- Config: configs/aot_gan/aot-gan_smpgan_4xb4_places-512x512.py
  In Collection: AOT-GAN
  Name: aot-gan_smpgan_4xb4_places-512x512
  Results:
  - Dataset: Places365-Challenge
    Metrics:
      PSNR: 19.01
      SSIM: 0.682
      l1 error: 7.07
    Task: Inpainting
  Weights: https://download.openmmlab.com/mmediting/inpainting/aot_gan/AOT-GAN_512x512_4x12_places_20220509-6641441b.pth
