Collections:
- Metadata:
    Architecture:
    - AOT-GAN
  Name: AOT-GAN
  Paper:
  - https://arxiv.org/pdf/2104.01431.pdf
  README: configs/aot_gan/README.md
Models:
- Config: configs/aot_gan/aot-gan_smpgan_4xb4_places-512x512.py
  In Collection: AOT-GAN
  Metadata:
    GPUs: 4 (GeForce GTX 1080 Ti)
    Training Data: PLACES
  Name: aot-gan_smpgan_4xb4_places-512x512
  Results:
  - Dataset: PLACES
    Metrics:
      PSNR: 19.01
      SSIM: 0.682
      l1 error: 7.07
    Task: Aot_gan
  Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmediting/inpainting/aot_gan/AOT-GAN_512x512_4x12_places_20220509-6641441b.pth
