Collections:
- Metadata:
    Architecture:
    - TOFlow
  Name: TOFlow
  Paper:
  - https://arxiv.org/abs/1711.09078
  README: configs/video_interpolators/tof/README.md
Models:
- Config: configs/video_interpolators/tof/tof_vfi_spynet_chair_nobn_1xb1_vimeo90k.py
  In Collection: TOFlow
  Metadata:
    Training Data: VIMEO90K
  Name: tof_vfi_spynet_chair_nobn_1xb1_vimeo90k
  Results:
  - Dataset: VIMEO90K
    Metrics:
      Vimeo90k-triplet:
        PSNR: 33.3294
        SSIM: 0.9465
    Task: Video_interpolators
  Weights: https://download.openmmlab.com/mmediting/video_interpolators/toflow/tof_vfi_spynet_chair_nobn_1xb1_vimeo90k_20220321-2fc9e258.pth
