Collections:
- Metadata:
    Architecture:
    - Instance-aware Image Colorization
  Name: Instance-aware Image Colorization
  Paper:
  - https://openaccess.thecvf.com/content_CVPR_2020/html/Su_Instance-Aware_Image_Colorization_CVPR_2020_paper.html
  README: configs/inst_colorization/README.md
Models: []
