Collections:
- Metadata:
    Architecture:
    - Instance-aware Image Colorization
  Name: Instance-aware Image Colorization
  Paper:
  - https://openaccess.thecvf.com/content_CVPR_2020/html/Su_Instance-Aware_Image_Colorization_CVPR_2020_paper.html
  README: configs/inst_colorization/README.md
Models:
- Config: configs/inst_colorization/inst-colorizatioon_full_official_cocostuff-256x256.py
  In Collection: Instance-aware Image Colorization
  Metadata:
    Training Data: Others
  Name: inst-colorizatioon_full_official_cocostuff-256x256
  Results:
  - Dataset: Others
    Metrics: {}
    Task: Inst_colorization
  Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmediting/inst_colorization/inst-colorizatioon_full_official_cocostuff-256x256-5b9d4eee.pth
