Collections:
- Name: AnimateDiff
  Paper:
    Title: 'AnimateDiff: Animate Your Personalized Text-to-Image Diffusion Models
      without Specific Tuning'
    URL: https://arxiv.org/abs/2307.04725
  README: configs/animatediff/README.md
  Task:
  - text2video
  Year: 2023
Models:
- Config: configs/animatediff/animatediff_ToonYou.py
  In Collection: AnimateDiff
  Name: animatediff_ToonYou
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://download.openxlab.org.cn/models/Masbfca/AnimateDiff/weight/toonyou_beta3.safetensors
- Config: configs/animatediff/animatediff_Lyriel.py
  In Collection: AnimateDiff
  Name: animatediff_Lyriel
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://download.openxlab.org.cn/models/Masbfca/AnimateDiff/weight/lyriel_v16.safetensors
- Config: configs/animatediff/animatediff_RcnzCartoon.py
  In Collection: AnimateDiff
  Name: animatediff_RcnzCartoon
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://download.openxlab.org.cn/models/Masbfca/AnimateDiff/weight/rcnzCartoon3d_v10.safetensors
- Config: configs/animatediff/animatediff_MajicMix.py
  In Collection: AnimateDiff
  Name: animatediff_MajicMix
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://download.openxlab.org.cn/models/Masbfca/AnimateDiff/weight/majicmixRealistic_v5Preview.safetensors
- Config: configs/animatediff/animatediff_RealisticVision.py
  In Collection: AnimateDiff
  Name: animatediff_RealisticVision
  Results:
  - Dataset: '-'
    Metrics: {}
    Task: Text2Video
  Weights: https://download.openxlab.org.cn/models/Masbfca/AnimateDiff/weight/realisticVisionV51_v20Novae.safetensors
- Config: configs/animatediff/animatediff_RealisticVision_v2.py
  In Collection: AnimateDiff
  Name: animatediff_RealisticVision_v2
  Results:
  - Dataset: WebVid
    Metrics: {}
    Task: Text2Video
  Weights: https://download.openxlab.org.cn/models/Masbfca/AnimateDiff/weight/mm_sd_v15_v2.ckpt
- Config: configs/animatediff/animatediff_RealisticVision_v1.py
  In Collection: AnimateDiff
  Name: animatediff_RealisticVision_v1
  Results:
  - Dataset: WebVid
    Metrics: {}
    Task: Text2Video
  - Dataset: WebVid
    Metrics: {}
    Task: Text2Video
  Weights: https://download.openxlab.org.cn/models/Masbfca/AnimateDiff/weight/mm_fromscratch_10Mval.ckpt
