Collections:
- Name: TTSR
  Paper:
    Title: Learning Texture Transformer Network for Image Super-Resolution
    URL: https://arxiv.org/abs/2006.04139
  README: configs/ttsr/README.md
  Task:
  - image super-resolution
  Year: 2020
Models:
- Config: configs/ttsr/ttsr-rec_x4c64b16_1xb9-200k_CUFED.py
  In Collection: TTSR
  Name: ttsr-rec_x4c64b16_1xb9-200k_CUFED
  Results:
  - Dataset: CUFED
    Metrics:
      PSNR: 25.2433
      SSIM: 0.7491
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/ttsr/ttsr-rec_x4_c64b16_g1_200k_CUFED_20210525-b0dba584.pth
- Config: configs/ttsr/ttsr-gan_x4c64b16_1xb9-500k_CUFED.py
  In Collection: TTSR
  Name: ttsr-gan_x4c64b16_1xb9-500k_CUFED
  Results:
  - Dataset: CUFED
    Metrics:
      PSNR: 24.6075
      SSIM: 0.7234
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/ttsr/ttsr-gan_x4_c64b16_g1_500k_CUFED_20210626-2ab28ca0.pth
