Collections:
- Metadata:
    Architecture:
    - TTSR
  Name: TTSR
  Paper:
  - https://arxiv.org/abs/2006.04139
  README: configs/ttsr/README.md
Models:
- Config: configs/ttsr/ttsr-rec_x4c64b16_200k-1xb9_CUFED.py
  In Collection: TTSR
  Metadata:
    GPUs: 1 (TITAN Xp)
    Training Data: CUFED
  Name: ttsr-rec_x4c64b16_200k-1xb9_CUFED
  Results:
  - Dataset: CUFED
    Metrics:
      CUFED:
        PSNR: 25.2433
        SSIM: 0.7491
    Task: Ttsr
  Weights: https://download.openmmlab.com/mmediting/restorers/ttsr/ttsr-rec_x4_c64b16_g1_200k_CUFED_20210525-b0dba584.pth
- Config: configs/ttsr/ttsr-gan_x4c64b16_500k-1xb9_CUFED.py
  In Collection: TTSR
  Metadata:
    GPUs: 1 (TITAN Xp)
    Training Data: CUFED
  Name: ttsr-gan_x4c64b16_500k-1xb9_CUFED
  Results:
  - Dataset: CUFED
    Metrics:
      CUFED:
        PSNR: 24.6075
        SSIM: 0.7234
    Task: Ttsr
  Weights: https://download.openmmlab.com/mmediting/restorers/ttsr/ttsr-gan_x4_c64b16_g1_500k_CUFED_20210626-2ab28ca0.pth
