Collections:
- Name: SAGAN
  Paper:
    Title: Self-attention generative adversarial networks
    URL: https://proceedings.mlr.press/v97/zhang19d.html
  README: configs/sagan/README.md
  Task:
  - conditional gans
  Year: 2019
Models:
- Config: configs/sagan/sagan_woReLUinplace_lr2e-4-ndisc5-1xb64_cifar10-32x32.py
  In Collection: SAGAN
  Name: sagan_woReLUinplace_lr2e-4-ndisc5-1xb64_cifar10-32x32
  Results:
  - Dataset: CIFAR10
    Metrics:
      FID: 10.503
      IS: 9.3217
      Iter: 400000.0
      Total Iters\*: 500000.0
      dist_step: 5.0
    Task: Conditional GANs
  - Dataset: CIFAR10
    Metrics:
      FID: 9.4252
      IS: 9.3174
      Iter: 480000.0
      Total Iters\*: 500000.0
      dist_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_woReUinplace_fid-iter480000_20210730_125449-d50568a4.pth
- Config: configs/sagan/sagan_wReLUinplace_lr2e-4-ndisc5-1xb64_cifar10-32x32.py
  In Collection: SAGAN
  Name: sagan_wReLUinplace_lr2e-4-ndisc5-1xb64_cifar10-32x32
  Results:
  - Dataset: CIFAR10
    Metrics:
      FID: 11.776
      IS: 9.2286
      Iter: 380000.0
      Total Iters\*: 500000.0
      dist_step: 5.0
    Task: Conditional GANs
  - Dataset: CIFAR10
    Metrics:
      FID: 10.7781
      IS: 9.2061
      Iter: 460000.0
      Total Iters\*: 500000.0
      dist_step: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sagan/sagan_cifar10_32_lr2e-4_ndisc5_b64x1_wReLUinplace_fid-iter460000_20210730_125155-cbefb354.pth
- Config: configs/sagan/sagan_woReLUinplace_Glr1e-4_Dlr4e-4_ndisc1-4xb64_imagenet1k-128x128.py
  In Collection: SAGAN
  Name: sagan_woReLUinplace_Glr1e-4_Dlr4e-4_ndisc1-4xb64_imagenet1k-128x128
  Results:
  - Dataset: ImageNet
    Metrics:
      FID: 36.7712
      IS: 31.5938
      Iter: 980000.0
      Total Iters\*: 1000000.0
      dist_step: 1.0
    Task: Conditional GANs
  - Dataset: ImageNet
    Metrics:
      FID: 34.7838
      IS: 28.4936
      Iter: 950000.0
      Total Iters\*: 1000000.0
      dist_step: 1.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sagan/sagan_imagenet1k_128_Glr1e-4_Dlr4e-4_ndisc1_b32x4_woReLUinplace_fid-iter950000_20210730_163431-d7916963.pth
- Config: configs/sagan/sagan_woReLUinplace-Glr1e-4_Dlr4e-4_noaug-ndisc1-8xb32-bigGAN-sch_imagenet1k-128x128.py
  In Collection: SAGAN
  Name: sagan_woReLUinplace-Glr1e-4_Dlr4e-4_noaug-ndisc1-8xb32-bigGAN-sch_imagenet1k-128x128
  Results:
  - Dataset: ImageNet
    Metrics:
      FID: 12.8295
      IS: 69.535
      Iter: 826000.0
      Total Iters\*: 1000000.0
      dist_step: 1.0
    Task: Conditional GANs
  - Dataset: ImageNet
    Metrics:
      FID: 12.8295
      IS: 69.535
      Iter: 826000.0
      Total Iters\*: 1000000.0
      dist_step: 1.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sagan/sagan_128_woReLUinplace_noaug_bigGAN_imagenet1k_b32x8_Glr1e-4_Dlr-4e-4_ndisc1_20210818_210232-3f5686af.pth
- Config: configs/sagan/sagan_cvt-studioGAN_cifar10-32x32.py
  In Collection: SAGAN
  Name: sagan_cvt-studioGAN_cifar10-32x32
  Results:
  - Dataset: CIFAR10
    Metrics:
      FID (Our Pipeline): 10.2011
      FID (StudioGAN): 14.009
      IS (Our Pipeline): 9.116
      IS (StudioGAN): 8.68
      Total Iters: 100000.0
      n_disc: 5.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sagan/sagan_32_cifar10_convert-studio-rgb_20210730_153321-080da7e2.pth
- Config: configs/sagan/sagan_128_cvt_studioGAN.py
  In Collection: SAGAN
  Name: sagan_128_cvt_studioGAN
  Results:
  - Dataset: ImageNet
    Metrics:
      FID (Our Pipeline): 40.1162
      FID (StudioGAN): 34.726
      IS (Our Pipeline): 27.367
      IS (StudioGAN): 29.848
      Total Iters: 1000000.0
      n_disc: 1.0
    Task: Conditional GANs
  Weights: https://download.openmmlab.com/mmediting/sagan/sagan_128_imagenet1k_convert-studio-rgb_20210730_153357-eddb0d1d.pth
