Collections:
- Name: EDSR
  Paper:
    Title: Enhanced Deep Residual Networks for Single Image Super-Resolution
    URL: https://arxiv.org/abs/1707.02921
  README: configs/edsr/README.md
  Task:
  - image super-resolution
  Year: 2017
Models:
- Config: configs/edsr/edsr_x2c64b16_1xb16-300k_div2k.py
  In Collection: EDSR
  Name: edsr_x2c64b16_1xb16-300k_div2k
  Results:
  - Dataset: Set5
    Metrics:
      PSNR: 35.7592
      SSIM: 0.9372
    Task: Image Super-Resolution
  - Dataset: Set14
    Metrics:
      PSNR: 31.429
      SSIM: 0.8874
    Task: Image Super-Resolution
  - Dataset: DIV2K
    Metrics:
      PSNR: 34.5896
      SSIM: 0.9352
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/edsr/edsr_x2c64b16_1x16_300k_div2k_20200604-19fe95ea.pth
- Config: configs/edsr/edsr_x3c64b16_1xb16-300k_div2k.py
  In Collection: EDSR
  Name: edsr_x3c64b16_1xb16-300k_div2k
  Results:
  - Dataset: Set5
    Metrics:
      PSNR: 32.3301
      SSIM: 0.8912
    Task: Image Super-Resolution
  - Dataset: Set14
    Metrics:
      PSNR: 28.4125
      SSIM: 0.8022
    Task: Image Super-Resolution
  - Dataset: DIV2K
    Metrics:
      PSNR: 30.9154
      SSIM: 0.8711
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/edsr/edsr_x3c64b16_1x16_300k_div2k_20200608-36d896f4.pth
- Config: configs/edsr/edsr_x4c64b16_1xb16-300k_div2k.py
  In Collection: EDSR
  Name: edsr_x4c64b16_1xb16-300k_div2k
  Results:
  - Dataset: Set5
    Metrics:
      PSNR: 30.2223
      SSIM: 0.85
    Task: Image Super-Resolution
  - Dataset: Set14
    Metrics:
      PSNR: 26.787
      SSIM: 0.7366
    Task: Image Super-Resolution
  - Dataset: DIV2K
    Metrics:
      PSNR: 28.9675
      SSIM: 0.8172
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/edsr/edsr_x4c64b16_1x16_300k_div2k_20200608-3c2af8a3.pth
