Collections:
- Metadata:
    Architecture:
    - Real-ESRGAN
  Name: Real-ESRGAN
  Paper:
  - https://arxiv.org/abs/2107.10833
  README: configs/restorers/real_esrgan/README.md
Models:
- Config: configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py
  In Collection: Real-ESRGAN
  Metadata:
    Training Data: Others
  Name: realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost
  Results:
  - Dataset: Others
    Metrics:
      Set5:
        PSNR: 28.0297
        SSIM: 0.8236
    Task: Restorers
  Weights: https://download.openmmlab.com/mmediting/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost_20210816-4ae3b5a4.pth
- Config: configs/restorers/real_esrgan/realesrgan_c64b23g32_12x4_lr1e-4_400k_df2k_ost.py
  In Collection: Real-ESRGAN
  Metadata:
    Training Data: Others
  Name: realesrgan_c64b23g32_12x4_lr1e-4_400k_df2k_ost
  Results:
  - Dataset: Others
    Metrics:
      Set5:
        PSNR: 26.2204
        SSIM: 0.7655
    Task: Restorers
  Weights: https://download.openmmlab.com/mmediting/restorers/real_esrgan/realesrgan_c64b23g32_12x4_lr1e-4_400k_df2k_ost_20211010-34798885.pth
