Collections:
- Name: DeblurGAN-v2
  Paper:
    Title: 'DeblurGAN-v2: Deblurring (Orders-of-Magnitude) Faster and Better'
    URL: https://arxiv.org/abs/1908.03826
  README: configs/deblurganv2/README.md
  Task:
  - image super-resolution
  Year: 2019
Models:
- Config: configs/deblurganv2/deblurganv2_fpn_inception.py
  In Collection: DeblurGAN-v2
  Name: deblurganv2_fpn_inception
  Results:
  - Dataset: GoProTestDataset
    Metrics:
      PSNR/<br/>SSIM:
        PSNR: 29.55
        SSIM: 0.934
    Task: Image Super-Resolution
  Weights: https://drive.google.com/uc?export=view&id=1UXcsRVW-6KF23_TNzxw-xC0SzaMfXOaR
- Config: configs/deblurganv2/deblurganv2_fpn_mobilenet.py
  In Collection: DeblurGAN-v2
  Name: deblurganv2_fpn_mobilenet
  Results:
  - Dataset: GoProTestDataset
    Metrics:
      PSNR/<br/>SSIM:
        PSNR: 28.17
        SSIM: 0.925
    Task: Image Super-Resolution
  Weights: https://drive.google.com/uc?export=view&id=1JhnT4BBeKBBSLqTo6UsJ13HeBXevarrU
