Collections:
- Metadata:
    Architecture:
    - LSGAN
  Name: LSGAN
  Paper:
  - https://openaccess.thecvf.com/content_iccv_2017/html/Mao_Least_Squares_Generative_ICCV_2017_paper.html
  README: configs/lsgan/README.md
Models:
- Config: configs/lsgan/lsgan_dcgan-archi_lr1e-3-1xb128-12Mimgs_celeba-cropped-64x64.py
  In Collection: LSGAN
  Metadata:
    Training Data: CELEBA
  Name: lsgan_dcgan-archi_lr1e-3-1xb128-12Mimgs_celeba-cropped-64x64
  Results:
  - Dataset: CELEBA
    Metrics:
      FID: 11.9258
      MS-SSIM: 0.3216
    Task: Lsgan
  Weights: https://download.openmmlab.com/mmgen/lsgan/lsgan_celeba-cropped_dcgan-archi_lr-1e-3_64_b128x1_12m_20210429_144001-92ca1d0d.pth
- Config: configs/lsgan/lsgan_dcgan-archi_lr1e-4-1xb128-12Mimgs_lsun-bedroom-64x64.py
  In Collection: LSGAN
  Metadata:
    Training Data: Others
  Name: lsgan_dcgan-archi_lr1e-4-1xb128-12Mimgs_lsun-bedroom-64x64
  Results:
  - Dataset: Others
    Metrics:
      FID: 30.739
      MS-SSIM: 0.0671
    Task: Lsgan
  Weights: https://download.openmmlab.com/mmgen/lsgan/lsgan_lsun-bedroom_dcgan-archi_lr-1e-4_64_b128x1_12m_20210429_144602-ec4ec6bb.pth
- Config: configs/lsgan/lsgan_dcgan-archi_lr1e-4-1xb64-10Mimgs_celeba-cropped-128x128.py
  In Collection: LSGAN
  Metadata:
    Training Data: CELEBA
  Name: lsgan_dcgan-archi_lr1e-4-1xb64-10Mimgs_celeba-cropped-128x128
  Results:
  - Dataset: CELEBA
    Metrics:
      FID: 38.3752
      MS-SSIM: 0.3691
    Task: Lsgan
  Weights: https://download.openmmlab.com/mmgen/lsgan/lsgan_celeba-cropped_dcgan-archi_lr-1e-4_128_b64x1_10m_20210429_144229-01ba67dc.pth
- Config: configs/lsgan/lsgan_lsgan-archi_lr1e-4-1xb64-10Mimgs_lsun-bedroom-128x128.py
  In Collection: LSGAN
  Metadata:
    Training Data: Others
  Name: lsgan_lsgan-archi_lr1e-4-1xb64-10Mimgs_lsun-bedroom-128x128
  Results:
  - Dataset: Others
    Metrics:
      FID: 51.55
      MS-SSIM: 0.0612
    Task: Lsgan
  Weights: https://download.openmmlab.com/mmgen/lsgan/lsgan_lsun-bedroom_lsgan-archi_lr-1e-4_128_b64x1_10m_20210429_155605-cf78c0a8.pth
