Collections:
- Name: DIC
  Paper:
    Title: Deep Face Super-Resolution with Iterative Collaboration between Attentive
      Recovery and Landmark Estimation
    URL: https://arxiv.org/abs/2003.13063
  README: configs/dic/README.md
  Task:
  - image super-resolution
  Year: 2020
Models:
- Config: configs/dic/dic_x8c48b6_4xb2-150k_celeba-hq.py
  In Collection: DIC
  Name: dic_x8c48b6_4xb2-150k_celeba-hq
  Results:
  - Dataset: CelebAHQ
    Metrics:
      PSNR: 25.2319
      SSIM: 0.7422
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/dic/dic_x8c48b6_g4_150k_CelebAHQ_20210611-5d3439ca.pth
- Config: configs/dic/dic_gan-x8c48b6_4xb2-500k_celeba-hq.py
  In Collection: DIC
  Name: dic_gan-x8c48b6_4xb2-500k_celeba-hq
  Results:
  - Dataset: CelebAHQ
    Metrics:
      PSNR: 23.6241
      SSIM: 0.6721
    Task: Image Super-Resolution
  Weights: https://download.openmmlab.com/mmediting/restorers/dic/dic_gan_x8c48b6_g4_500k_CelebAHQ_20210625-3b89a358.pth
