Collections:
- Name: Unsupervised Representation Learning with Deep Convolutional Generative Adversarial
    Networks
  Paper:
    Title: Unsupervised Representation Learning with Deep Convolutional Generative
      Adversarial Networks
    URL: https://arxiv.org/abs/1511.06434
  README: configs/dcgan/README.md
  Task:
  - unconditional gans
  Year: 2016
Models:
- Config: configs/dcgan/dcgan_Glr4e-4_Dlr1e-4_1xb128-5kiters_mnist-64x64.py
  In Collection: Unsupervised Representation Learning with Deep Convolutional Generative
    Adversarial Networks
  Name: dcgan_Glr4e-4_Dlr1e-4_1xb128-5kiters_mnist-64x64
  Results:
  - Dataset: MNIST(64x64)
    Metrics:
      MS-SSIM: 0.1395
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmediting/dcgan/dcgan_mnist-64_b128x1_Glr4e-4_Dlr1e-4_5k_20210512_163926-207a1eaf.pth
- Config: configs/dcgan/dcgan_1xb128-300kiters_celeba-cropped-64.py
  In Collection: Unsupervised Representation Learning with Deep Convolutional Generative
    Adversarial Networks
  Name: dcgan_1xb128-300kiters_celeba-cropped-64
  Results:
  - Dataset: CelebA-Cropped
    Metrics:
      MS-SSIM: 0.2899
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmediting/dcgan/dcgan_celeba-cropped_64_b128x1_300kiter_20210408_161607-1f8a2277.pth
- Config: configs/dcgan/dcgan_1xb128-5epoches_lsun-bedroom-64x64.py
  In Collection: Unsupervised Representation Learning with Deep Convolutional Generative
    Adversarial Networks
  Name: dcgan_1xb128-5epoches_lsun-bedroom-64x64
  Results:
  - Dataset: LSUN-Bedroom
    Metrics:
      MS-SSIM: 0.2095
    Task: Unconditional GANs
  Weights: https://download.openmmlab.com/mmediting/dcgan/dcgan_lsun-bedroom_64_b128x1_5e_20210408_161713-117c498b.pth
